@startuml
|教务处|
start
:安排考试;
:考试安排表;
|#AntiqueWhite|教师|
:出卷;
fork
:A、B试卷;
fork again
:打印审批表;
|系主任|
:审批签字;
:打印审批表;
end fork
|教务处|
:打印试卷;
:试卷;
|学生|
:参加考试;
:答卷;
|教师|
:阅卷出成绩;
split
:成绩单;
|教务处|
if (有不及格?) then (no)
stop
else
:安排补考;
split
:补考安排表;
detach
split again
end split
endif
split again
|教师|
:答卷;
:装订成档;
end split
:期末流程结束;
@enduml