@startuml
title 选课
actor users
participant lesson
participant student
participant lesson
participant chooselesson
== 教师选课 ==
users -> lesson:查看课程列表
activate lesson
activate users
lesson ->lesson:以未被选方式排列
activate lesson
lesson ->chooselesson:选择课程
deactivate lesson
deactivate lesson
activate chooselesson
chooselesson --> users:返回选课成功消息与具体信息
deactivate chooselesson
deactivate users
== 学生选课 ==
users -> lesson:查看课程列表
activate lesson
activate users
lesson ->lesson:以未被选方式排列
activate lesson
lesson ->chooselesson:选择课程
deactivate lesson
deactivate lesson
alt 该课程已先有教师选中
    activate chooselesson
    chooselesson --> users:返回选课成功消息与具体信息
else 该课程没有教师教授
    chooselesson --> users:返回选课失败消息与具体原因
    deactivate chooselesson
    deactivate users

opt 修改选课
== 学生修改选课 ==
    users -> student:查看学生信息
    activate student
    activate users
    student -> chooselesson:查看已选课程
    activate chooselesson
    deactivate student
    chooselesson -> chooselesson:delete
    activate chooselesson
    chooselesson --> users
    deactivate chooselesson
    deactivate chooselesson
    deactivate users
== 教师修改选课 ==
    users -> lesson:查看教师信息
    activate lesson
    activate users
    lesson -> chooselesson:查看已选课程
    activate chooselesson
    deactivate lesson
    chooselesson -> chooselesson:delete
    alt 已有学生选择此课程
        activate chooselesson
        chooselesson --> users:修改选课失败，已有学生\n选择此课程，请联系管理员
    else 无学生选择此课程
        chooselesson --> users:修改选课成功
    end
    deactivate chooselesson
    deactivate chooselesson
    deactivate users
end
@enduml